# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
dist: trusty
cache: packages

addons:
  apt:
    packages:
      - ggalt

r:
  - oldrel
  - release
  - devel

after_success:
    - Rscript -e 'covr::codecov()'
