# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
#sudo: false
dist: trusty
cache: packages

r:
  - oldrel
  - release
  - devel

addons:
  apt:
    packages:
      - binutils
      - libproj-dev
      - gdal-bin

after_success:
    - Rscript -e 'covr::codecov()'
