# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
#sudo: false
dist: trusty
cache: packages

r:
  - oldrel
  - release
  - devel

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libproj-dev
      - libgeos-dev
      - libgdal-dev

r_packages:
  - boot
  - dplyr
  - lubridate
  - purrr
  - rlang
  - tibble
  - tidyr
  - covr
  - ggplot2
  - ggalt
  - testthat
  - knitr
  - rmarkdown

after_success:
    - Rscript -e 'covr::codecov()'
